### ISSUE TITLE
[Bug] Comment in style not ended (index.html)

### ISSUE THREAD

**Issue by KwiatekMiki** [benjamin060708/Cow-clicker#1]
## You forgot to end the comment in code, oops.
![img](https://user-images.githubusercontent.com/79092746/205136556-94f99c39-ed41-41f4-9aa6-0d8e1bc75a24.png)
Where: index.html > html > head > style > body > user-select
### How to fix it?
Way #1: Change `user-select: none; /* Non-prefixed version, currently` to `user-select: none; /* Non-prefixed version, currently */`
Way #2: Merge my pull request (#2)
#### Comments
nope

**Comment by Bongs237** [comment]
fixed with #2 (thx for finding this)
